---
################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 2/8/2023
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
#
# REFERENCE PAGES FOR THE BELOW TASKS CAN BE FOUND BY USING THE FOLLOWING LINK
# https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/
#
# THIS PLAYBOOK USES THE "hosts" FILE ONLY AND NO OTHER VARIABLE FILE
#
# NOTE: THIS PLAYBOOK IS USED TO INSTALL MODIFY THE DEVICE CERTIFICATE ON THE BIGIP
#
# EXAMPLE hosts FILE ENTRY BELOW
# 
#  [tenant1]
#    big-ip-lab1 hostname=big-ip-lab1.f5net def_admin=admin def_root=root ten1_ip=10.154.85.124 def_admin_pass=admin def_root_pass=default new_root_pass=<NEW PASSWORD> new_admin_pass=<NEW PASSWORD>	
#
#
# Usage: ansible-playbook -vvv device-cert-declarative.yaml
#
# SEE THE .json FILE IN THE /JSON DIRECTORY FOR CONTENTS OF THE DEVICE CERTIFICATE.
#
# ALSO SEE THE FOLLOWING ARTICLE FOR GENERATING THE DEVICE CERTIFICATE VIA OPENSSL
#   https://support.f5.com/csp/article/K14534
#
################################################################################################
  - hosts: tenant1
    collections:
      - f5networks.f5_bigip
    connection: httpapi

    vars:
      ansible_host: "{{ten1_ip}}"
      ansible_user: "{{def_admin}}"
      ansible_httpapi_password: "{{new_admin_pass}}"
      ansible_network_os: f5networks.f5_bigip.bigip
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: yes
      ansible_command_timeout: 60
      ansible_httpapi_validate_certs: no

    tasks:
      - name: Update original Device Certificate
        bigip_do_deploy:
          content: "{{ lookup('file', 'json/declaredevicecertkey.json') }}"
        register: new_device_certificate
