---
  - hosts: tenant1
    collections:
      - f5networks.f5_bigip
    connection: httpapi

    vars:
      ansible_host: "{{ten1_ip}}"
      ansible_user: "{{def_admin}}"
      ansible_httpapi_password: "{{new_admin_pass}}"
      ansible_network_os: f5networks.f5_bigip.bigip
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: yes
      ansible_command_timeout: 60
      ansible_httpapi_validate_certs: no

    tasks:
      - name: Update original Device Certificate
        bigip_do_deploy:
          content: "{{ lookup('file', 'json/declaredevicecertkey.json') }}"
        register: new_device_certificate
