---
################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 2/8/2023
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
#
# REFERENCE PAGES FOR THE BELOW TASKS CAN BE FOUND BY USING THE FOLLOWING LINK
# https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/
#
# THIS PLAYBOOK USES THE "hosts" FILE ONLY AND NO OTHER VARIABLE FILE
#
# NOTE: THIS PLAYBOOK IS USED TO INSTALL THE UPLOADED .rpm FILES FOR DO, TELEMETRY OR APPSVCS
#
# NOTE: THIS .rpm FILE HAS TO BE INSTALLED ON THE BIGIP IN ORDER TO RUN A PLAYBOOK THAT UPDATES/CHANGES THE DEVICE CERTIFICATE.
#
# EXAMPLE hosts FILE ENTRY BELOW
# 
#  [tenant1]
#    big-ip-lab1 hostname=big-ip-lab1.f5net def_admin=admin def_root=root ten1_ip=10.154.85.124 def_admin_pass=admin def_root_pass=default new_root_pass=<NEW PASSWORD> new_admin_pass=<NEW PASSWORD>	
#
#
# Usage: ansible-playbook -vvv install-rpm-declarative.yaml 
#
################################################################################################

  - hosts: tenant1
    collections: 
      - f5networks.f5_bigip
    connection: httpapi

    vars:
      ansible_host: "{{ten1_ip}}"
      ansible_user: "{{def_admin}}"
      ansible_httpapi_password: "{{new_admin_pass}}"
      ansible_network_os: f5networks.f5_bigip.bigip
      ansible_httpapi_use_ssl: yes
      ansible_httpapi_validate_certs: no

    tasks: 
      - name: Install RPM
        bigip_lx_package: 
          package: f5-declarative-onboarding-1.35.0-6.noarch.rpm
          #package: f5-telemetry-1.32.0-2.noarch.rpm
          #package: f5-appsvcs-3.42.0-5.noarch.rpm
          retain_package_file: yes
