################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 11/19/2022
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
# INSTALL F5OS COLLECTION FOR ANSIBLE USING THE FOLLOWING LINK 
#     "https://galaxy.ansible.com/f5networks/f5os"
# 
# RUN THE FOLLOWING COMMAND FROM WITHIN "/root/.ansible/collections"
#     ansible-galaxy collection install f5networks.f5os
#
# REFERENCE PAGES FOR THE BELOW TASKS CAN BE FOUND BY USING THE FOLLOWING LINK
# https://clouddocs.f5.com/training/community/rseries-training/html/introduction.html
#
# NOTE: For any API calls to the rSeries F5OS layer it is important to include the header Content-Type application/yang-data+json and use port 8888 
#
# USAGE: ansible-playbook -vvv t-build-imperative.yaml
#
################################################################################################


  - hosts: rseries
    connection: local
    gather_facts: false
    vars:
      provider:
        server: "{{mgmt_ip}}"
        user: "{{f5admin}}"
        password: "{{f5admin_pass}}"
        validate_certs: no

    collections:
      - f5networks.f5_bigip

    tasks:
      - name: Create New Tenant
        uri:
          url: https://{{mgmt_ip}}:8888/restconf/data/f5-tenants:tenants
          user: "{{ f5admin }}"
          password: "{{f5admin_pass}}"
          method: POST
          headers:
            Content-Type: application/yang-data+json
            Accept: application/yang-data+json
          force_basic_auth: yes
          force: yes
          status_code: 201
          return_content: true
          validate_certs: no
          body_format: json
          body: "{{ lookup('ansible.builtin.file','json/tenant-shell.json') }}"
        register: Tenant_Shell

      - name: Wait 30 seconds before deploying Tenant
        ansible.builtin.wait_for:
          timeout: 30
        delegate_to: localhost

      - name: Deploy New Tenant
        uri:
          url: https://{{mgmt_ip}}:8888/restconf/data/f5-tenants:tenants/tenant=tenant1/config/running-state
          user: "{{ f5admin }}"
          password: "{{f5admin_pass}}"
          method: PATCH
          headers:
            Content-Type: application/yang-data+json
            Accept: application/yang-data+json
          force_basic_auth: yes
          force: yes
          status_code: 204
          return_content: true
          validate_certs: no
          body_format: json
          body: "{{ lookup('ansible.builtin.file','json/tenant-deploy.json') }}"
        register: Tenant_Deploy
