#################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 12/2/2022
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
# INSTALL F5OS COLLECTION FOR ANSIBLE USING THE FOLLOWING LINK 
#     "https://galaxy.ansible.com/f5networks/f5os"
# 
# RUN THE FOLLOWING COMMAND FROM WITHIN "/root/.ansible/collections"
#     ansible-galaxy collection install f5networks.f5os
#
# REFERENCE PAGE FOR TASK IS "https://clouddocs.f5.com/products/orchestration/ansible/devel/f5os/modules_3_0/f5os_tenant_image_module.html#f5os-tenant-image-module-3"
#
# NOTE: THIS PLAYBOOK CONNECTS TO THE rSeries ON PORT "8888", YOU WILL NEED TO USE THE FOLLOWING PORT VARIABLE
#    "ansible_httpapi_port: 8888" 
#
# NOTE: THIS PLAYBOOK BUILDS A NEW TENANT UTILIZING A SEPERATE INVENTORY FILE CALLED "tenant_vars.yaml
#  
# Usage: ansible-playbook -vvv t-build-declarative.yaml -i /<path>/hosts -i /<path>/tenant_vars.yaml
#
#################################################################################################


  - hosts: rseries
    collections:
      - f5networks.f5os
    connection: httpapi

    vars:
      ansible_host: "{{mgmt_ip}}"
      ansible_user: "{{f5admin}}"
      ansible_httpapi_password: "{{f5admin_pass}}"
      ansible_httpapi_port: 8888
      ansible_network_os: f5networks.f5os.f5os
      ansible_httpapi_use_ssl: yes
      ansible_httpapi_validate_certs: no

    tasks:
      - name: Tenant Build
        f5os_tenant:
          name: "{{ tenant_1 }}"
          image_name: "{{ t_image_15_1_7 }}"
          nodes: "{{ nodes_1 }}"
          mgmt_ip: "{{ mgmt_ip_1 }}"
          mgmt_prefix: 24
          mgmt_gateway: "{{ mgmt_gw }}"
          vlans: "{{ vlans_1 }}"
          cpu_cores: "{{ cpu_4 }}"
          memory: "{{ mem_12288 }}"
          running_state: "{{ state_depl }}"
