################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 11/19/2022
#
# THIS PLAYBOOK IS ANOTHER VERSION, ALSO DECLARATIVE, BUT DOES NOT USE A VARIABLE FILE FOR THE TASK.
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
# INSTALL F5OS COLLECTION FOR ANSIBLE USING THE FOLLOWING LINK 
#     "https://galaxy.ansible.com/f5networks/f5os"
# 
# RUN THE FOLLOWING COMMAND FROM WITHIN "/root/.ansible/collections"
#     ansible-galaxy collection install f5networks.f5os
#
# REFERENCE PAGE FOR TASK IS "https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/module_index.html"
#
# NOTE: THIS PLAYBOOK CONNECTS TO THE rSeries ON PORT "8888", YOU WILL NEED TO USE THE FOLLOWING PORT VARIABLE
#    "ansible_httpapi_port: 8888" 
#
# NOTE: TO RUN THIS FILE USE THE FOLLOWING COMMAND FROM WITHIN THE PLAYBOOK LOCATION
#       ansible-playbook -vvv t-image-upload-declarative-old.yaml
#
################################################################################################


  - hosts: rseries
    collections:
      - f5networks.f5os
    connection: httpapi

    vars:
      ansible_host: "{{mgmt_ip}}"
      ansible_user: "{{f5admin}}"
      ansible_httpapi_password: "{{f5admin_pass}}"
      ansible_httpapi_port: 8888
      ansible_network_os: f5networks.f5os.f5os
      ansible_httpapi_use_ssl: yes
      ansible_httpapi_validate_certs: no

    tasks:
      - name: Import tenant image 'BIGIP-15.1.7-0.0.6.ALL-F5OS.qcow2.zip.bundle' onto the F5OS device
        f5os_tenant_image:
          image_name: BIGIP-15.1.7-0.0.6.ALL-F5OS.qcow2.zip.bundle
          remote_host: "192.168.1.10"
          remote_user: root
          remote_password: default
          remote_path: /home/ansible/rseries/post/uploads/
          local_path: images/tenant
          state: import

