---
################################################################################################
# CREATED and TESTED SUCCESSFULLY BY STEVEN MEISENZAHL 2/8/2023
#
# THERE IS NO SUPPORT FOR THIS SOLUTION, USE AT YOUR OWN RISK
# 
#
# REFERENCE PAGES FOR THE BELOW TASKS CAN BE FOUND BY USING THE FOLLOWING LINK
# https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/
#
# THIS PLAYBOOK USES THE "hosts" FILE ONLY AND NO OTHER VARIABLE FILE
#
# NOTE: THE FILE "f5-declarative-onboarding-1.35.0-6.noarch.rpm" NEEDS TO BE IN THE SAME DIRECTORY AS THE PLAYBOOK .YAML FILE
#
# EXAMPLE hosts FILE ENTRY BELOW
# 
#  [tenant1]
#    big-ip-lab1 hostname=big-ip-lab1.f5net def_admin=admin def_root=root ten1_ip=10.154.85.124 def_admin_pass=admin def_root_pass=default new_root_pass=<NEW PASSWORD> new_admin_pass=<NEW PASSWORD>	
#
#
# Usage: ansible-playbook -vvv upload-do-package-imparative.yaml 
#
################################################################################################

  - hosts: tenant1
    connection: local
    gather_facts: false
    vars:
      provider:
        server: "{{ten1_ip}}"
        user: "{{def_admin}}"
        password: "{{new_admin_pass}}"
        validate_certs: no
        LEN: 1770532
        FN: f5-declarative-onboarding-1.35.0-6.noarch.rpm

    collections:
      - f5networks.f5_bigip

    tasks:
      - name: Upload RPM file to Bigip
        ansible.builtin.uri:
          url: https://{{ten1_ip}}/mgmt/tm/util/bash
          method: POST
          user: "{{def_admin}}"
          password: "{{new_admin_pass}}"
          headers:
            Content-Type: application/json
          body_format: raw
          body: "{\n\t\"command\": \"run\", \"utilCmdArgs\": \"-c \\\"cd /var/config/rest/downloads/ && curl -sk -LJO https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.35.0/f5-declarative-onboarding-1.35.0-6.noarch.rpm\\\"\"\n}"
          force_basic_auth: yes
          timeout: 300
          return_content: true
          validate_certs: no
        register: lx_upload
