---
rseries:
  vars:
    tenant_1: big-ip-lab1
    t_image_15_1_7: "BIGIP-15.1.7-0.0.6.ALL-F5OS.qcow2.zip.bundle"
    mgmt_ip_1: 10.154.85.124
    mgmt_gw_1: 10.154.85.254
    nodes_1: 1
    state_depl_1: deployed
    mem_1: 14848
    cpu_1: 4
    vlans_1: [ 501,3010,3011 ]

    tenant_2: big-ip-lab2
    t_image_15_1_8: "BIGIP-15.1.8-0.0.7.ALL-F5OS.qcow2.zip.bundle"
    mgmt_ip_2: 10.154.85.125
    mgmt_gw_2: 10.154.85.254
    nodes_2: 1
    state_depl_2: deployed
    mem_2: 12848
    cpu_2: 4
    vlans_2: [ 502,3010,3011 ]
...
