---
  - hosts: rseries
    connection: local
    gather_facts: false
    vars: 
      provider: 
        server: "{{mgmt_ip}}"
        user: "{{f5admin}}"
        password: "{{f5admin_pass}}"
        validate_certs: no

    collections:
      - f5networks.f5_bigip

    tasks:
      - name: GET LACP Info
        ansible.builtin.uri:
          url: https://{{mgmt_ip}}:8888/restconf/data/openconfig-lacp:lacp
          user: "{{ f5admin }}"
          password: "{{ f5admin_pass }}"
          method: GET
          headers:
            Content-Type: application/yang-data+json
          force_basic_auth: yes
          status_code: 200
          return_content: true
          validate_certs: no
