---
  - hosts: rseries
    connection: httpapi
    gather_facts: false
    vars: 
      ansible_host: "{{ mgmt_ip }}"
      ansible_user: "{{ f5admin }}"
      ansible_httpapi_password: "{{ f5admin_pass }}"
      ansible_network_os: f5networks.f5os.f5os
      ansible_httpapi_use_ssl: yes

    collections:
      - f5networks.f5_bigip

    tasks:
      - name: GET Portgroups Info
        ansible.builtin.uri:
          url: https://{{mgmt_ip}}:8888/restconf/data/f5-portgroup:portgroups
          method: GET
          headers:
            Content-Type: application/yang-data+json
          force_basic_auth: yes
          status_code: 200
          return_content: true
          validate_certs: no
