---

- name: Test device Info
  hosts: bigips
  gather_facts: false
  connection: local

  vars:
    provider:
      password: "{{ansible_pass}}"
      server: "{{ ansible_host }}"
      user: "{{ansible_user}}"
      validate_certs: no
      server_port: 443

  tasks:
  - name: Checking Version
    bigip_device_info:
      gather_subset:
        - system-info
      provider: "{{ provider }}"
    delegate_to: localhost
    register: results

  - name: Checking Interfaces
    bigip_command:
      commands: show net interface
      provider: "{{ provider }}"
    delegate_to: localhost
    register: interfaces

  - name: Checking CPU health
    bigip_command:
      commands: show sys cpu | grep "System CPU Usage" -A3
      provider: "{{ provider }}"
    delegate_to: localhost
    register: cpu

  - name: Checking Memory health
    bigip_command:
      commands: show sys memory | egrep "System Memory Information|Memory Used" -A1
      provider: "{{ provider }}"
    delegate_to: localhost
    register: memory

  - name: Checking Disk Health
    bigip_command:
      commands: run util bash -c df -h
      provider: "{{ provider }}"
    delegate_to: localhost
    register: disk

  - name: Deleting file if already exist.
    file:
      path: ../outputs/health.txt
      state: absent 

  - name: Creating a file to save the systme Health.
    file:
      path: ../outputs/health.txt
      state: touch
    register: file

  - name: generating final file
    blockinfile:
      path: "{{ file.dest }}"
      marker: "######## Device Health of {{ provider.server }}  ################"
      #insertafter: "##### Device Health "
      block: |
       System running version: {{ results['system_info']['product_version'] }}
       Interfaces status: {{ interfaces.stdout_lines[0] | to_nice_json }}
       CPU Utilization is: {{ cpu.stdout_lines[0]| to_nice_json }}
       Memory Info: {{ memory.stdout_lines[0] | to_nice_json  }}
       Disk space Info: {{ disk.stdout_lines[0] | to_nice_json  }}
